version: '3'
services:
  php:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.2.10-zts-bullseye'
    image: php-devs
    ports:
      - '8000:8000'
    environment:
      APP_ENV: 'production'
      PHP_VERSION: '8.2.10-zts-bullseye'
    deploy:
      resources:
        limits:
          cpus: '1' # Limite de CPU para 0,5 núcleos (50%)
          memory: 512M # Limite de memória para 512 megabytes
        reservations:
          cpus: '0.5' # Reserva de CPU para 0,2 núcleos (20%)
          memory: 256M # Reserva de memória para 256 megabytes
    volumes:
      - ./public:/var/www/app/public
      - ./docker/supervisord:/etc/supervisor/conf.d/
      - ./docker/php/extra-php.ini:/usr/local/etc/php/conf.d/99_extra.ini
      # - ./docker/php/extra-php.ini.semjit:/usr/local/etc/php/conf.d/99_extra.ini
