<?php
echo "<h1>Testes Disponíveis</h1>";
echo "<p>";
echo "<a href='/info.php' target='_blank'>Informações do PHP</a><br>";
echo "<hr>";
echo "<a href='/teste0.php' target='_blank'>Teste 0</a><br>";
echo "<a href='/teste1.php' target='_blank'>Teste 1</a><br>";
echo "<a href='/teste2.php' target='_blank'>Teste 2</a><br>";
echo "<a href='/teste3.php' target='_blank'>Teste 3</a><br>";
echo "<a href='/teste4.php' target='_blank'>Teste 4</a><br>";
echo "<a href='/teste5.php' target='_blank'>Teste 5</a><br>";
echo "<hr><h2>Resultados</h2>";
echo "<a href='/jit_ativo_teste0.html' target='_blank'>Teste 0 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste0.html' target='_blank'>Teste 0 | JIT Inativo</a><br>";
echo "<hr>";
echo "<a href='/jit_ativo_teste1.html' target='_blank'>Teste 1 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste1.html' target='_blank'>Teste 1 | JIT Inativo</a><br>";
echo "<hr>";
echo "<a href='/jit_ativo_teste2.html' target='_blank'>Teste 2 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste2.html' target='_blank'>Teste 2 | JIT Inativo</a><br>";
echo "<hr>";
echo "<a href='/jit_ativo_teste3.html' target='_blank'>Teste 3 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste3.html' target='_blank'>Teste 3 | JIT Inativo</a><br>";
echo "<hr>";
echo "<a href='/jit_ativo_teste4.html' target='_blank'>Teste 4 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste4.html' target='_blank'>Teste 4 | JIT Inativo</a><br>";
echo "<hr>";
echo "<a href='/jit_ativo_teste5.html' target='_blank'>Teste 5 | JIT Ativo</a><br>";
echo "<a href='/jit_inativo_teste5.html' target='_blank'>Teste 5 | JIT Inativo</a><br>";
echo "</p>";
